# Generated by Django 4.2.2 on 2023-07-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='qualtity',
            new_name='quantity',
        ),
    ]
