# Generated by Django 4.2.2 on 2023-10-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_created_at_alter_orders_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='New', max_length=200),
        ),
    ]
